<?php

//  Load the shared file needed before this page continues.
require_once __DIR__ . '/includes/functions.php';
requireLogin();
$id = (int) ($_GET['id'] ?? 0);
$hasDirectPackage = columnExists($pdo, 'payments', 'package_id');
$directPackageSelect = $hasDirectPackage ? 'COALESCE(pk_direct.package_name, pk_member.package_name)' : 'pk_member.package_name';
$directPackageJoin = $hasDirectPackage ? 'LEFT JOIN packages pk_direct ON pk_direct.package_id = p.package_id' : '';

$payment = one(
    $pdo,
    "SELECT p.*, m.full_name, m.member_number, {$directPackageSelect} AS package_name,
        ms.start_date AS membership_start, ms.end_date AS membership_end
     FROM payments p
     JOIN members m ON m.member_id = p.member_id
     LEFT JOIN memberships ms ON ms.membership_id = p.membership_id
     LEFT JOIN packages pk_member ON pk_member.package_id = ms.package_id
     {$directPackageJoin}
     WHERE p.payment_id = ?",
    [$id],
);

if (!$payment || $payment['status'] !== 'Completed') {
    http_response_code(404);
    die('A completed payment receipt is not available.');
}

if (currentUser()['role'] === 'Member') {
    $member = getMemberByUser($pdo, currentUser()['id']);
    if (!$member || (int) $member['member_id'] !== (int) $payment['member_id']) {
        http_response_code(403);
        die('Not allowed.');
    }
}

    // Converts receipt text into a character set supported by the lightweight PDF writer.
 
function pdfSafe(string $text): string
{
    // Student function step: This is the start of pdfSafe(). The lines below do the main work of this helper.
    $converted = function_exists('iconv') ? iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $text) : $text;
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], (string) $converted);
}

    // Builds the simple payment-receipt PDF document.

function buildSimplePdf(array $lines): string
{
    // Student function step: This is the start of buildSimplePdf(). The lines below do the main work of this helper.
    $commands = ["BT", "/F1 20 Tf", "60 790 Td", '(' . pdfSafe('POWERFIT') . ') Tj', "/F1 10 Tf"];
    $yStep = -28;
    foreach ($lines as $line) {
        $commands[] = "0 {$yStep} Td";
        $commands[] = '(' . pdfSafe($line) . ') Tj';
    }
    $commands[] = 'ET';
    $stream = implode("\n", $commands);

    $objects = [];
    $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    $objects[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
    $objects[3] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>';
    $objects[4] = '<< /Length ' . strlen($stream) . ">>\nstream\n" . $stream . "\nendstream";
    $objects[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';

    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $number => $object) {
        $offsets[$number] = strlen($pdf);
        $pdf .= $number . " 0 obj\n" . $object . "\nendobj\n";
    }

    $xrefOffset = strlen($pdf);
    $pdf .= "xref\n0 6\n0000000000 65535 f \n";
    for ($i = 1; $i <= 5; $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n{$xrefOffset}\n%%EOF";

    return $pdf;
}

$lines = [
    'Verified gym payment receipt',
    'Reference: ' . $payment['reference_number'],
    'Date: ' . date('d M Y, h:i A', strtotime($payment['payment_date'])),
    'Member: ' . $payment['full_name'] . ' (' . $payment['member_number'] . ')',
    'Package: ' . ($payment['package_name'] ?? 'General payment'),
    'Method: ' . $payment['payment_method'],
    'Status: Completed',
    'Amount: LKR ' . number_format((float) $payment['amount'], 2),
];

if (columnExists($pdo, 'payments', 'card_last4') && !empty($payment['card_last4'])) {
    $lines[] = 'Card ending: ' . $payment['card_last4'];
}
if (columnExists($pdo, 'payments', 'card_holder_name') && !empty($payment['card_holder_name'])) {
    $lines[] = 'Cardholder: ' . $payment['card_holder_name'];
}

if ($payment['membership_start']) {
    $lines[] = 'Membership period: ' . shortDate($payment['membership_start']) . ' - ' . shortDate($payment['membership_end']);
}
$lines[] = '';
$lines[] = 'Generated by PowerFit';

$pdf = buildSimplePdf($lines);
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="powerfit-' . preg_replace('/[^A-Za-z0-9-]/', '', $payment['reference_number']) . '.pdf"');
header('Content-Length: ' . strlen($pdf));
echo $pdf;
exit;
