<?php

//Tiny dependency-free PDF builder for the local academic PowerFit project.
//Supports branded headings, wrapped summary rows and compact multi-page tables.


// Escapes characters before writing them into the generated PDF content stream.

function pdfEscapeText(string $text): string
{
    // Student function step: This is the start of pdfEscapeText(). The lines below do the main work of this helper.
    $converted = function_exists('iconv')
        ? iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $text)
        : $text;

    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], (string) $converted);
}

 //Wraps long PDF text so it fits inside the available page width.

function pdfWrapText(string $text, int $width = 82): array
{
    // Student function step: This is the start of pdfWrapText(). The lines below do the main work of this helper.
    $text = trim(preg_replace('/\s+/', ' ', $text) ?? $text);
    if ($text === '') {
        return [''];
    }

    return explode("\n", wordwrap($text, max(8, $width), "\n", true));
}

// Builds one PDF text-drawing command with the requested font size and position.

function pdfTextCommand(
    float $x,
    float $y,
    string $text,
    int $size = 10,
    bool $bold = false,
    array $rgb = [0.08, 0.08, 0.08],
): string {
    // Student function step: This is the start of pdfTextCommand(). The lines below do the main work of this helper.
    $font = $bold ? 'F2' : 'F1';
    [$r, $g, $b] = $rgb;

    return sprintf(
        "BT /%s %d Tf %.3f %.3f %.3f rg %.2f %.2f Td (%s) Tj ET",
        $font,
        $size,
        $r,
        $g,
        $b,
        $x,
        $y,
        pdfEscapeText($text),
    );
}

// Estimates how many text characters can fit inside a PDF table column.

function pdfTableColumnCharacterWidth(float $width): int
{
    // Student function step: This is the start of pdfTableColumnCharacterWidth(). The lines below do the main work of this helper.
    return max(6, (int) floor(($width - 12) / 5.2));
}

 //Builds a branded multi-page PowerFit PDF from headings, key-value data and tables.
 
function buildPowerFitPdf(string $title, string $subtitle, array $sections): string
{
    // Student function step: This is the start of buildPowerFitPdf(). The lines below do the main work of this helper.
    $pageWidth = 595;
    $pageHeight = 842;
    $margin = 48;
    $tableWidth = 499;
    $contentTop = 690;
    $contentBottom = 62;
    $lineHeight = 15;

    $pages = [];
    $commands = [];
    $y = $contentTop;
    $pageNumber = 1;

    // Starts a new PDF page and draws the repeated PowerFit page header/footer.
    $startPage = function () use (&$commands, &$y, &$pageNumber, $pageWidth, $margin, $contentTop, $title, $subtitle): void {
        // Student function step: This anonymous helper runs a small task that is used only inside this current file/function.
        $commands = [];
        $commands[] = '0.93 0.93 0.93 rg 0 0 595 842 re f';
        $commands[] = '0.055 0.055 0.055 rg 0 742 595 100 re f';
        $commands[] = pdfTextCommand($margin, 805, 'POWERFIT', 12, true, [1, 1, 1]);
        $commands[] = pdfTextCommand($margin, 780, $title, 22, true, [1, 1, 1]);
        if ($subtitle !== '') {
            $commands[] = pdfTextCommand($margin, 760, $subtitle, 9, false, [0.83, 0.83, 0.83]);
        }
        $commands[] = pdfTextCommand($margin, 34, 'Generated by PowerFit', 8, false, [0.35, 0.35, 0.35]);
        $commands[] = pdfTextCommand($pageWidth - 100, 34, 'Page ' . $pageNumber, 8, false, [0.35, 0.35, 0.35]);
        $y = $contentTop;
    };

    // Finishes the current PDF page and stores its drawing commands.
    $finishPage = function () use (&$commands, &$pages, &$pageNumber): void {
        // Student function step: This anonymous helper runs a small task that is used only inside this current file/function.
        $pages[] = implode("\n", $commands);
        $pageNumber++;
    };

    // Draws a consistent section heading bar inside the PDF.
    $drawSectionHeading = function (string $heading, bool $continued = false) use (&$commands, &$y, $margin): void {
        // Student function step: This anonymous helper runs a small task that is used only inside this current file/function.
        $label = strtoupper($heading . ($continued ? ' - CONTINUED' : ''));
        $commands[] = '0.055 0.055 0.055 rg ' . $margin . ' ' . ($y - 4) . ' 499 26 re f';
        $commands[] = pdfTextCommand($margin + 12, $y + 5, $label, 9, true, [1, 1, 1]);
        $y -= 38;
    };

    // Draws the header row for a PDF table before table data is printed.
    $drawTableHeader = function (array $headers, array $widths) use (&$commands, &$y, $margin): void {
        // Student function step: This anonymous helper runs a small task that is used only inside this current file/function.
        $x = $margin;
        $headerHeight = 28;
        foreach ($headers as $index => $header) {
            $width = (float) ($widths[$index] ?? 60);
            $commands[] = sprintf('0.055 0.055 0.055 rg %.2f %.2f %.2f %.2f re f', $x, $y - $headerHeight, $width, $headerHeight);
            $commands[] = sprintf('0.20 0.20 0.20 RG 0.5 w %.2f %.2f %.2f %.2f re S', $x, $y - $headerHeight, $width, $headerHeight);
            $commands[] = pdfTextCommand($x + 6, $y - 18, (string) $header, 7, true, [1, 1, 1]);
            $x += $width;
        }
        $y -= $headerHeight;
    };

    $startPage();

    foreach ($sections as $section) {
        $heading = (string) ($section['heading'] ?? '');
        $rows = $section['rows'] ?? [];
        $table = $section['table'] ?? null;

        if ($heading !== '') {
            if ($y < $contentBottom + 54) {
                $finishPage();
                $startPage();
            }
            $drawSectionHeading($heading);
        }

        foreach ($rows as $row) {
            if (is_string($row)) {
                $label = '';
                $value = $row;
            } else {
                $label = (string) ($row['label'] ?? '');
                $value = (string) ($row['value'] ?? '');
            }

            $wrapped = pdfWrapText($value, $label !== '' ? 67 : 84);
            $needed = max(1, count($wrapped)) * $lineHeight + 8;
            if ($y - $needed < $contentBottom) {
                $finishPage();
                $startPage();
                if ($heading !== '') {
                    $commands[] = pdfTextCommand($margin, $y, $heading . ' (continued)', 10, true, [0.15, 0.15, 0.15]);
                    $y -= 22;
                }
            }

            if ($label !== '') {
                $commands[] = pdfTextCommand($margin, $y, $label, 9, true, [0.24, 0.24, 0.24]);
                $valueX = $margin + 138;
            } else {
                $valueX = $margin;
            }

            foreach ($wrapped as $index => $line) {
                $commands[] = pdfTextCommand($valueX, $y - ($index * $lineHeight), $line, 9, false, [0.08, 0.08, 0.08]);
            }
            $y -= $needed;
            $commands[] = sprintf('0.83 0.83 0.83 RG 0.4 w %.2f %.2f m %.2f %.2f l S', $margin, $y + 3, $margin + 499, $y + 3);
        }

        if (is_array($table)) {
            $headers = array_values($table['headers'] ?? []);
            $tableRows = array_values($table['rows'] ?? []);
            $widths = array_values($table['widths'] ?? []);

            if ($headers && $tableRows) {
                if (!$widths || abs(array_sum($widths) - $tableWidth) > 0.5) {
                    $columnCount = max(1, count($headers));
                    $widths = array_fill(0, $columnCount, $tableWidth / $columnCount);
                }

                if ($y < $contentBottom + 80) {
                    $finishPage();
                    $startPage();
                    if ($heading !== '') {
                        $drawSectionHeading($heading, true);
                    }
                }
                $drawTableHeader($headers, $widths);

                foreach ($tableRows as $row) {
                    $cells = array_values(is_array($row) ? $row : [(string) $row]);
                    $wrappedCells = [];
                    $maxLines = 1;
                    foreach ($headers as $index => $_header) {
                        $cell = (string) ($cells[$index] ?? '');
                        $wrappedCells[$index] = pdfWrapText($cell, pdfTableColumnCharacterWidth((float) $widths[$index]));
                        $maxLines = max($maxLines, count($wrappedCells[$index]));
                    }

                    $rowHeight = max(28, 10 + ($maxLines * 11));
                    if ($y - $rowHeight < $contentBottom) {
                        $finishPage();
                        $startPage();
                        if ($heading !== '') {
                            $drawSectionHeading($heading, true);
                        }
                        $drawTableHeader($headers, $widths);
                    }

                    $x = $margin;
                    foreach ($headers as $index => $_header) {
                        $width = (float) $widths[$index];
                        $commands[] = sprintf('0.985 0.985 0.985 rg %.2f %.2f %.2f %.2f re f', $x, $y - $rowHeight, $width, $rowHeight);
                        $commands[] = sprintf('0.82 0.82 0.82 RG 0.45 w %.2f %.2f %.2f %.2f re S', $x, $y - $rowHeight, $width, $rowHeight);
                        foreach ($wrappedCells[$index] as $lineIndex => $line) {
                            $commands[] = pdfTextCommand($x + 6, $y - 16 - ($lineIndex * 11), $line, 7, false, [0.08, 0.08, 0.08]);
                        }
                        $x += $width;
                    }
                    $y -= $rowHeight;
                }
            } elseif ($headers && !$tableRows) {
                $commands[] = pdfTextCommand($margin, $y, 'No items have been added yet.', 9, false, [0.35, 0.35, 0.35]);
                $y -= 24;
            }
        }

        $y -= 10;
    }

    $finishPage();

    $objects = [];
    $pageObjectNumbers = [];
    $contentObjectNumbers = [];

    $nextObject = 5;
    foreach ($pages as $index => $stream) {
        $pageObjectNumbers[$index] = $nextObject++;
        $contentObjectNumbers[$index] = $nextObject++;
    }

    $kids = implode(' ', array_map(fn($number) => $number . ' 0 R', $pageObjectNumbers));
    $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
    $objects[2] = '<< /Type /Pages /Kids [' . $kids . '] /Count ' . count($pages) . ' >>';
    $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
    $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

    foreach ($pages as $index => $stream) {
        $pageNumberObject = $pageObjectNumbers[$index];
        $contentNumberObject = $contentObjectNumbers[$index];
        $objects[$pageNumberObject] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ' . $contentNumberObject . ' 0 R >>';
        $objects[$contentNumberObject] = '<< /Length ' . strlen($stream) . ">>\nstream\n" . $stream . "\nendstream";
    }

    ksort($objects);
    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $number => $object) {
        $offsets[$number] = strlen($pdf);
        $pdf .= $number . " 0 obj\n" . $object . "\nendobj\n";
    }

    $maxObject = max(array_keys($objects));
    $xrefOffset = strlen($pdf);
    $pdf .= "xref\n0 " . ($maxObject + 1) . "\n0000000000 65535 f \n";
    for ($i = 1; $i <= $maxObject; $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i] ?? 0);
    }
    $pdf .= "trailer\n<< /Size " . ($maxObject + 1) . " /Root 1 0 R >>\nstartxref\n{$xrefOffset}\n%%EOF";

    return $pdf;
}

    // Sends the generated PDF to the browser with download headers.
 
function outputPowerFitPdf(string $pdf, string $fileName)
{
    // Student function step: This is the start of outputPowerFitPdf(). The lines below do the main work of this helper.
    $safe = preg_replace('/[^A-Za-z0-9._-]/', '-', $fileName) ?: 'powerfit-document.pdf';
    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $safe . '"');
    header('Content-Length: ' . strlen($pdf));
    header('X-Content-Type-Options: nosniff');
    echo $pdf;
    exit;
}
